version: "3"

services:
  flask:
    image:  pierrickm/flask-lecopain
    container_name: flask
    restart: always
    environment:
      - APP_NAME=Lecopain
    expose:
      - 8080
    volumes:
      -  /usr/share/db/lecopain:/db

  nginx:
    image:  pierrickm/nginx-lecopain
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes: 
     - ../certs:/etc/nginx/certs
