<reset-urls>
    <div>
    </div>
    <script>
        localStorage.removeItem('search_product_url');
        localStorage.removeItem('search_customer_url');
        localStorage.removeItem('search_subscription_url');
        localStorage.removeItem('search_shipment_url');
    </script>
</reset-urls>