version: "3"

services:
  flask:
    image:  pierrickm/flask-lecopain
    container_name: flask-lecopain
    restart: always
    environment:
      - APP_NAME=Lecopain
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/share/certs/nginx:/etc/nginx/certs
    restart: always
    depends_on:
      - postgres

  postgres:
    image:  pierrickm/postgres-lecopain
    container_name: postgres-lecopain
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - lecopain-db:/var/lib/postgresql/data
    restart: always 

volumes:
  lecopain-db:
    external: true
